apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mycodexvantaos-ai-ensemble/deployment.yaml
  - mycodexvantaos-core-auth/deployment.yaml
  - mycodexvantaos-data-vector-store/deployment.yaml
