apiVersion: v1
kind: Service
metadata:
  name: mycodexvantaos-secret-vault
  namespace: mycodexvantaos
  labels:
    app: mycodexvantaos-secret-vault
    part-of: mycodexvantaos
spec:
  selector:
    app: mycodexvantaos-secret-vault
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP