apiVersion: v1
kind: Service
metadata:
  name: mycodexvantaos-app-ui
  namespace: mycodexvantaos
  labels:
    app: mycodexvantaos-app-ui
    part-of: mycodexvantaos
spec:
  selector:
    app: mycodexvantaos-app-ui
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP